Segmenting and Clustering Neighborhoods in Toronto
week3

scrape the following Wikipedia page
(https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

wiki = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
wiki1 = BeautifulSoup(wiki.content, 'html.parser')

create the dataframe from wikipedia page

In [20]:
body = wiki1.find('tbody')
rows = body.select('tr')
row = [r.get_text() for r in rows]
df = pd.DataFrame(row)
df1 = df[0].str.split('\n', expand=True)
df1.head(11)

   0         1                 2                 3 4
0     Postcode           Borough     Neighbourhood
1          M1A      Not assigned      Not assigned
2          M2A      Not assigned      Not assigned
3          M3A        North York         Parkwoods
4          M4A        North York  Victoria Village
5          M5A  Downtown Toronto      Harbourfront
6          M5A  Downtown Toronto       Regent Park
7          M6A        North York  Lawrence Heights
8          M6A        North York    Lawrence Manor
9          M7A      Queen's Park      Not assigned
10         M8A      Not assigned      Not assigned

In [22]:
df2 = df1.rename(columns=df1.iloc[0])
df3 = df2.drop(df2.index[0])
df3.head(11)

     Postcode           Borough     Neighbourhood
1         M1A      Not assigned      Not assigned
2         M2A      Not assigned      Not assigned
3         M3A        North York         Parkwoods
4         M4A        North York  Victoria Village
5         M5A  Downtown Toronto      Harbourfront
6         M5A  Downtown Toronto       Regent Park
7         M6A        North York  Lawrence Heights
8         M6A        North York    Lawrence Manor
9         M7A      Queen's Park      Not assigned
10        M8A      Not assigned      Not assigned
11        M9A         Etobicoke  Islington Avenue

ignore cells with a borough that is Not assigned

In [25]:
df4 = df3[df3.Borough != 'Not assigned']
df4.head(11)

     Postcode           Borough     Neighbourhood
3         M3A        North York         Parkwoods
4         M4A        North York  Victoria Village
5         M5A  Downtown Toronto      Harbourfront
6         M5A  Downtown Toronto       Regent Park
7         M6A        North York  Lawrence Heights
8         M6A        North York    Lawrence Manor
9         M7A      Queen's Park      Not assigned
11        M9A         Etobicoke  Islington Avenue
12        M1B       Scarborough             Rouge
13        M1B       Scarborough           Malvern
15        M3B        North York   Don Mills North

combine neighborhoods

In [26]:
df5 = df4.groupby(['Postcode', 'Borough'], sort = False).agg(','.join)
df5.reset_index(inplace = True)
df5.head(11)

   Postcode           Borough                    Neighbourhood
0       M3A        North York                        Parkwoods
1       M4A        North York                 Victoria Village
2       M5A  Downtown Toronto         Harbourfront,Regent Park
3       M6A        North York  Lawrence Heights,Lawrence Manor
4       M7A      Queen's Park                     Not assigned
5       M9A         Etobicoke                 Islington Avenue
6       M1B       Scarborough                    Rouge,Malvern
7       M3B        North York                  Don Mills North
8       M4B         East York   Woodbine Gardens,Parkview Hill
9       M5B  Downtown Toronto          Ryerson,Garden District
10      M6B        North York                        Glencairn

change the value of the neighborhood

In [27]:
df6 = df5.replace("Not assigned", "Queen's Park")
df6.head()

  Postcode           Borough                    Neighbourhood
0      M3A        North York                        Parkwoods
1      M4A        North York                 Victoria Village
2      M5A  Downtown Toronto         Harbourfront,Regent Park
3      M6A        North York  Lawrence Heights,Lawrence Manor
4      M7A      Queen's Park                     Queen's Park

the number of rows

In [28]:
df6.shape

(103, 3)