# Latitude & Longitude

Scrape the following Wikipedia page
(https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M)

In [89]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

wiki = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
wiki1 = BeautifulSoup(wiki.content, 'html.parser')

Create the table from wikipedia page

In [90]:
table = wiki1.find('table', {'class': 'wikitable sortable'})

Create the dataframe using pandas

In [91]:
column = ["Postal Code", "Borough", "Neighborhood"]
df = pd.read_html(str(table), skiprows=1)
df = pd.DataFrame.from_dict(df[0])
df.columns = column
df.head(11)

   Postal Code           Borough      Neighborhood
0          M2A      Not assigned      Not assigned
1          M3A        North York         Parkwoods
2          M4A        North York  Victoria Village
3          M5A  Downtown Toronto      Harbourfront
4          M5A  Downtown Toronto       Regent Park
5          M6A        North York  Lawrence Heights
6          M6A        North York    Lawrence Manor
7          M7A      Queen's Park      Not assigned
8          M8A      Not assigned      Not assigned
9          M9A         Etobicoke  Islington Avenue
10         M1B       Scarborough             Rouge

Ignore cells with a borough that is Not assigned

In [92]:
df1 = df[df.Borough != 'Not assigned']
df1.head(11)

   Postal Code           Borough      Neighborhood
1          M3A        North York         Parkwoods
2          M4A        North York  Victoria Village
3          M5A  Downtown Toronto      Harbourfront
4          M5A  Downtown Toronto       Regent Park
5          M6A        North York  Lawrence Heights
6          M6A        North York    Lawrence Manor
7          M7A      Queen's Park      Not assigned
9          M9A         Etobicoke  Islington Avenue
10         M1B       Scarborough             Rouge
11         M1B       Scarborough           Malvern
13         M3B        North York   Don Mills North

Combine neighborhoods

In [93]:
df2 = df1.groupby(["Postal Code", "Borough"], sort = False).agg(','.join)
df2.reset_index(inplace = True)
df2.head(11)

   Postal Code           Borough                     Neighborhood
0          M3A        North York                        Parkwoods
1          M4A        North York                 Victoria Village
2          M5A  Downtown Toronto         Harbourfront,Regent Park
3          M6A        North York  Lawrence Heights,Lawrence Manor
4          M7A      Queen's Park                     Not assigned
5          M9A         Etobicoke                 Islington Avenue
6          M1B       Scarborough                    Rouge,Malvern
7          M3B        North York                  Don Mills North
8          M4B         East York   Woodbine Gardens,Parkview Hill
9          M5B  Downtown Toronto          Ryerson,Garden District
10         M6B        North York                        Glencairn

Change the value of the neighborhood

In [94]:
df3 = df2.replace("Not assigned", "Queen's Park")
df3.head(11)

   Postal Code           Borough                     Neighborhood
0          M3A        North York                        Parkwoods
1          M4A        North York                 Victoria Village
2          M5A  Downtown Toronto         Harbourfront,Regent Park
3          M6A        North York  Lawrence Heights,Lawrence Manor
4          M7A      Queen's Park                     Queen's Park
5          M9A         Etobicoke                 Islington Avenue
6          M1B       Scarborough                    Rouge,Malvern
7          M3B        North York                  Don Mills North
8          M4B         East York   Woodbine Gardens,Parkview Hill
9          M5B  Downtown Toronto          Ryerson,Garden District
10         M6B        North York                        Glencairn

The number of rows

In [24]:
df3.shape

(103, 3)

Latitude & Longitude
Read csv file from URL

In [95]:
df_l = pd.read_csv("http://cocl.us/Geospatial_data")
df_l.head(11)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304

Add geospatial coordinates

In [96]:
ll = pd.merge(df3, df_l, how='inner', left_on="Postal Code", right_on="Postal Code")
ll.head(11)

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Harbourfront,Regent Park",43.654260,-79.360636
3,M6A,North York,"Lawrence Heights,Lawrence Manor",43.718518,-79.464763
4,M7A,Queen's Park,Queen's Park,43.662301,-79.389494
5,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
6,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
7,M3B,North York,Don Mills North,43.745906,-79.352188
8,M4B,East York,"Woodbine Gardens,Parkview Hill",43.706397,-79.309937
9,M5B,Downtown Toronto,"Ryerson,Garden District",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073